name: deploy-pages

triggers:
  push:
    branches:
      - pages

jobs:
  deploy:
    image: alios-8u
    steps:
      - uses: checkout
      - uses: deploy-pages
        inputs:
          deploy-dir: frontend
          production-branch: pages
